# Samenvoegen van de verschillende ophalingen per soort

Vermits het ophalen van de general observaties in verschillende sessies is opgehaald, moeten de verschillende .csv files gecombineerd worden. </br>
Duplicates in deze gecombineerde dataset, door dubbel ophalen van data, worden verwijderd. 
Clean data wordt (per soort nl. halsbandparkieten en boomklevers) in een aparte map gezet.

In [1]:
import pandas as pd
import os
from random import randint


###########################################################################################################################################
species_id = 70
folder_path = "./scraped_data/"
folder_path_clean = "./scraped_data/cleaned/"
temp_combined_csv = "temp_combined_observations_delete_me.csv"

# Find all CSV files containing "observations_{species_id}" in their filename
csv_files = [f for f in os.listdir(folder_path) if f"observations_{species_id}" in f and f.endswith(".csv")]
# Sort the files, prioritizing those containing "pages_1- because the header needs to be put on top
csv_files.sort(key=lambda x: 0 if "pages_1-" in x else 1)

# Append all CSV files into a single new CSV file
with open(temp_combined_csv, "w") as outfile:
    for i, file in enumerate(csv_files):
        file_path = os.path.join(folder_path, file)
        with open(file_path, "r") as infile:
                outfile.write(infile.read())

# Load the appended CSV file into a DataFrame
combined_df = pd.read_csv(temp_combined_csv)

# Remove duplicates
cleaned_df = combined_df.drop_duplicates()

# Save the cleaned DataFrame to a new CSV file
cleaned_df.to_csv(os.path.join(folder_path_clean, f"observations_general_{species_id}_clean.csv"), index=False)

# Optional: Remove the temporary combined file
os.remove(temp_combined_csv)

In [6]:
df = pd.read_csv(f"{folder_path_clean}observations_general_{species_id}_clean.csv")

df.describe()

                 id    location_id   observer_id           page
count  1.039370e+05  102291.000000  1.034580e+05  103937.000000
mean   1.664224e+08   56822.454429  7.922206e+04    2079.240030
std    8.582433e+07   83628.293048  9.611901e+04    1200.166889
min    4.482060e+05   23088.000000  1.360000e+02       1.000000
25%    8.278936e+07   27542.000000  4.070800e+04    1040.000000
50%    1.663381e+08   30289.000000  4.417500e+04    2079.000000
75%    2.308681e+08   42336.000000  8.235400e+04    3119.000000
max    3.369673e+08  724090.000000  1.059786e+06    4158.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103937 entries, 0 to 103936
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           103937 non-null  object
 1   id             103937 non-null  int64
 2   amount_manner  103937 non-null  object
 3   location       103937 non-null  object
 4   location_id    102291 non-null  float64
 5   observer_name  103937 non-null  object
 6   observer_id    103458 non-null  float64
 7   validation     103937 non-null  object
 8   page           103937 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 7.1+ MB

In [8]:
df.head()

,date,id,amount_manner,location,location_id,observer_name,observer_id,validation,page
0,2024-12-31 17:50,336207061,1 baltsend / zingend,Ivoz-Ramet (Li√®ge),42217.0,Charly Farinelle,40377.0,goedgekeurd (automatische validatie),1
1,2024-12-31,336186286,1 baltsend / zingend,Bioul (Namur),42452.0,Didier Cavelier,44246.0,goedgekeurd (automatische validatie),1
2,2024-12-31 06:53,336212374,"1 baltsend / zingend, gehoord",Veerle - Aartsbroek (Antwerpen),29060.0,Anthony Hollebeke,63875.0,goedgekeurd (automatische validatie),1
3,2024-12-31,336182552,1 slaapplaats,Grenspark Kalmthoutse Heide (Antwerpen),678810.0,Wouter Vanwesenbeeck,41768.0,goedgekeurd (automatische validatie),1
4,2024-12-31,336182078,1 slaapplaats,Grenspark Kalmthoutse Heide (Antwerpen),678810.0,Bram Vogels,40112.0,goedgekeurd (automatische validatie),1